#!/bin/sh

set -e

cabal configure --prefix=/opt/scrz
cabal build

rm -rf img
mkdir -p img img/opt/scrz/lib img/etc/systemd/system

cabal copy --destdir=img

cp /usr/lib/libgmp.so.10 img/opt/scrz/lib/

cp systemd/* img/etc/systemd/system/

OUTPUT=scrz-$(git describe | tr -d v)-coreos.tar.gz
tar czf $OUTPUT -C img .

rm -rf img
