#!/bin/sh
set -e


VOLUME="/var/lib/scrz/workspace/arch/rootfs"

if test -d "$VOLUME"; then
  echo "Image already exists. If you want to delete the image, use this command:"
  echo
  echo "  btrfs subvolume delete $VOLUME"
  echo

  exit
fi


test -d "$(dirname "$VOLUME")" || mkdir -p "$(dirname "$VOLUME")"
btrfs subvol create "$VOLUME"
pacstrap -i -c -d "$VOLUME" base


systemd-nspawn -D "$VOLUME" pacman-key --init
systemd-nspawn -D "$VOLUME" rm /etc/machine-id /etc/securetty
systemd-nspawn -D "$VOLUME" systemd-firstboot --timezone UTC --root-password=root


MANIFEST="$(mktemp)"
chmod 644 $MANIFEST
cat script/systemd-os-image-manifest-template | \
    sed -e "s/{{name}}/arch-$(date +%Y.%m.%d)-64bit/" > $MANIFEST


scrz pack-image $MANIFEST arch
rm $MANIFEST
