#!/bin/sh

set -e


# Download & install the scrz package
# ----------------------------------------------------------------------------

curl -so /tmp/scrz.tar.gz https://caurea.org/scrz.tar.gz
rm -rf /opt/scrz
tar -xf /tmp/scrz.tar.gz -C /


# Start the node supervisor
# ----------------------------------------------------------------------------

systemctl daemon-reload
systemctl start scrz-node-supervisor.service


# Cleanup
# ----------------------------------------------------------------------------
rm /tmp/scrz.tar.gz
